version: '3.8'

services:
  redis:
    container_name: swat-tools_redis
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    restart: always
  celery:
    container_name: swat-tools_celery
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: celery -A swatapps worker -l info
    volumes:
      - $HOST_CELERY_LOG_DIR:/var/log/swat-tools
      - user_data:/home/swatapps/web/user_data
    depends_on:
      - redis
    env_file:
      - .env.prod
      - .env.prod.db
  celery-beat:
    container_name: swat-tools_celery-beat
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: celery -A swatapps beat -l info
    volumes:
      - user_data:/home/swatapps/web/user_data
    depends_on:
      - redis
    env_file:
      - .env.prod
      - .env.prod.db
  db:
    container_name: swat-tools_db
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    env_file:
      - .env.prod.db
  app:
    container_name: swat-tools_app
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn swatapps.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - $HOST_DJANGO_LOG_DIR:/var/log/swat-tools
      - static_data:/home/swatapps/web/staticfiles
      - user_data:/home/swatapps/web/user_data
    expose:
      - 8000
    depends_on:
      - db
      - redis
    restart: always
    env_file:
      - .env.prod
      - .env.prod.db
  nginx:
    container_name: swat-tools_nginx
    build: ./nginx
    volumes:
      - static_data:/home/swatapps/web/staticfiles
    ports:
      - 8003:80
    depends_on:
      - app

volumes:
  mysql_data:
  redis_data:
  static_data:
  user_data:
