version: '3.8'

services:
  redis:
    container_name: swat-tools_redis
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    restart: always
  celery:
    container_name: swat-tools_celery
    build: ./app
    command: celery -A swatapps worker -l info
    volumes:
      - ./app/:/usr/src/app/
      - $HOST_CELERY_LOG_DIR:/var/log/swat-tools
    depends_on:
      - redis
    env_file:
      - .env.dev
      - .env.dev.db
  celery-beat:
    container_name: swat-tools_celery-beat
    build: ./app
    command: celery -A swatapps beat -l info
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - redis
    env_file:
      - .env.dev
      - .env.dev.db
  db:
    container_name: swat-tools_db
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    env_file:
      - ./.env.dev.db
  app:
    container_name: swat-tools_app
    build: ./app
    command: 'python manage.py runserver 0.0.0.0:8000'
    volumes:
      - ./app/:/usr/src/app/
      - $HOST_DJANGO_LOG_DIR:/var/log/swat-tools
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    restart: always
    env_file:
      - ./.env.dev
      - ./.env.dev.db

volumes:
  mysql_data:
  redis_data:
