"""
Django settings for swatapps project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from logging.config import dictConfig
from pathlib import Path


# Admins (name, email)

ADMINS = [admin.split(',') for admin in os.environ['ADMINS'].split(';')]


# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = str(Path(__file__).resolve().parent.parent)
PROJECT_DIR = str(Path(__file__).parents[2])
LOGS_DIR = os.path.join(PROJECT_DIR, 'logs/django/')
SETTINGS_DIR = os.path.dirname(__file__)
USER_UPLOAD_DIR = os.path.join(PROJECT_DIR, 'user_upload/')
USER_RESULT_DIR = os.path.join(PROJECT_DIR, 'user_result/')


# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ['SECRET_KEY']
AWS_ACCESS_KEY = os.environ['AWS_ACCESS_KEY_ID']
AWS_ACCESS_SECRET = os.environ['AWS_SECRET_ACCESS_KEY']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'fieldswat',
    'luuchecker',
    's3upload',
    'swatluu',
    'swatusers',
    'templates',
    'uncertainty'
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'swatapps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(PROJECT_DIR, 'templates').replace('\\', '/'),
            os.path.join(PROJECT_DIR, 's3direct/templates').replace('\\', '/')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'swatapps.wsgi.application'


# Celery

BROKER_URL = os.environ['REDIS_HOST_PORT']
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_HIJACK_ROOT_LOGGER = False


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': os.environ['MYSQL_HOST'],
        'NAME': os.environ['MYSQL_DATABASE'],
        'USER': os.environ['MYSQL_USER'],
        'PASSWORD': os.environ['MYSQL_PASSWORD'],
        'PORT': os.environ['MYSQL_PORT']
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Media files

MEDIA_ROOT = USER_UPLOAD_DIR
MEDIA_URL = '/media/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(PROJECT_DIR, 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = (os.path.join(PROJECT_DIR, 'static_storage'),)


# User model
AUTH_USER_MODEL = 'swatusers.SwatUser'
AUTHENTICATION_BACKENDS = [
    'swatusers.backends.EmailAuthBackend',
    'django.contrib.auth.backends.ModelBackend'
]


# File upload settings
FILE_UPLOAD_TEMP_DIR = '/tmp'
FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o775
FILE_UPLOAD_PERMISSIONS = 0o664


# Login URL
LOGIN_URL = '/login'


# Google recaptcha site/secret keys
NORECAPTCHA_SITE_KEY = os.environ['NORECAPTCHA_SITE_KEY']
NORECAPTCHA_SECRET_KEY = os.environ['NORECAPTCHA_SECRET_KEY']


# Email
EMAIL_USE_TLS = True
EMAIL_HOST = os.environ['EMAIL_HOST']
EMAIL_HOST_USER = os.environ['EMAIL_USER']
EMAIL_HOST_PASSWORD = os.environ['EMAIL_PASSWORD']
EMAIL_PORT = os.environ['EMAIL_PORT']
DEFAULT_FROM_EMAIL = os.environ['EMAIL_USER']


# API key
APIKEY = os.environ['API_KEY']


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
