"""
Django settings for swatapps project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from .base import *

# SECURITY WARNING: don't run with debug turned on in production:
DEBUG = True

ALLOWED_HOSTS = ['0.0.0.0', 'localhost']