"""
Django settings for swatapps project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import settings_secret

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_DIR = os.path.dirname(__file__)
TMP_DIR = '/tmp'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = settings_secret.get_secret_key()

# Google recaptcha public/private keys
RECAPTCHA_PUBLIC_KEY = settings_secret.get_norecaptcha_site_key()
RECAPTCHA_PRIVATE_KEY = settings_secret.get_norecaptcha_secret_key()

NOCAPTCHA = True

# Run recaptcha over ssl
#RECAPTCHA_USE_SSL = True

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True
#SECURE_SSL_REDIRECT = True
#SESSION_COOKIE_SECURE = True
SESSION_COOKIE_AGE = 1800
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True
#CSRF_COOKIE_SECURE = True

ALLOWED_HOSTS = ['saraswat-swat.rcac.purdue.edu']

ADMINS = [('Ben Hancock', 'hancocb@purdue.edu')]

FILE_UPLOAD_PERMISSIONS = '0o644'
MAX_UPLOAD_SIZE = '1073741824'

LOGIN_URL = '/login'

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap3',
    'captcha',
    'swatusers',
    'swatluu',
    'luuchecker',
    'uncertainty',
    'fieldswat',
)

AUTH_USER_MODEL = 'swatusers.SwatUser'

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

AUTHENTICATION_BACKENDS = (
    'swatusers.backends.EmailAuthBackend',
)

ROOT_URLCONF = 'swatapps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.dirname(__file__), 'templates').replace('\\', '/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'swatapps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file': SETTINGS_DIR + '/my.cnf',
        },
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Media files

MEDIA_ROOT = BASE_DIR
MEDIA_URL = '/media/'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_ROOT = BASE_DIR + '/static/'
STATIC_URL = '/static/'
STATIC_PATH = '/static/'
STATIC_PATH_DIR = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static_storage'),
)


# Email

EMAIL_USE_TLS = True
EMAIL_HOST = settings_secret.get_email_host()
EMAIL_HOST_USER = settings_secret.get_email_user()
EMAIL_HOST_PASSWORD = settings_secret.get_email_password()
EMAIL_PORT = settings_secret.get_email_port()
DEFAULT_FROM_EMAIL = settings_secret.get_email_user()